// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cognito_identity_pool_id = 'us-east-1:20e96c3f-2cf7-467d-b03a-50b9194f2e3a';
var aws_cognito_region = 'us-east-1';
var aws_content_delivery = 'enable';
var aws_content_delivery_bucket = 'bigpinkcupcake-hosting-mobilehub-2029373897';
var aws_content_delivery_bucket_region = 'us-east-1';
var aws_content_delivery_cloudfront = 'enable';
var aws_content_delivery_cloudfront_domain = 'dtxt5isum7fnx.cloudfront.net';
var aws_mobile_analytics_app_id = 'bddfbf3955f44dd896e56d22cbcb91a9';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = '4fa6a952-3464-46f8-8da8-bf71ea2a78e6';
var aws_project_name = 'bigPinkCupcake';
var aws_project_region = 'us-east-1';
var aws_resource_name_prefix = 'bigpinkcupcake-mobilehub-2029373897';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
